### ISSUE TITLE
Remote exchange is selling...

### ISSUE THREAD

**Issue by kinther** [kinther/federation2#33]
INFO:root:Cessna does not sell Hypnotapes, moving on...
INFO:root:Checking if Diamond is selling Hypnotapes...
INFO:root:Remote exchange is selling Hypnotapes.
INFO:root:Paper does not sell Hypnotapes, moving on...
INFO:root:Piper does not sell Hypnotapes, moving on...
INFO:root:Blackbird does not sell Hypnotapes, moving on...
INFO:root:Cirrus does not sell Hypnotapes, moving on...
INFO:root:Zen does not sell Hypnotapes, moving on...
INFO:root:Phoenix does not sell Hypnotapes, moving on...

Something happened between Diamond selling and moving on to other planets.  Improve log output to indicate why.

**Comment by pdub206** [comment]
Added log messages to v2.3 branch to identify where in the loop this is happening.

**Comment by pdub206** [comment]
Due to checkIfSelling function and commodity being being defined threshold.

Added logging information to let user know this is why planet was skipped.

Will update README to reflect this threshold and advice to have multiple planets that can sell items if need be.
